### ISSUE TITLE
release v4.0-beta checklist

### ISSUE THREAD

**Issue by debugtalk** [httprunner/httprunner#1228]
HttpRunner v4.0 发布前需要完成如下工作：

## 文档
- [x] 项目概述介绍
- [x] QuickStart 快手上手文档
- [x] HttpRunner v4 用户文档整体结构
- [x] golang vs python 版本特性对比
- [x] v4 宣传文章

## 项目管理
- [x] github labels 分类
- [x] issue 管理机制（milestone、projects）
- [x] [v4 版本规划](https://github.com/orgs/httprunner/projects/1/views/1)

## 功能开发
- [x] #1188
- [x] #1200
- [x] 将 hrp 仓库合并到 httprunner
- [x] 将 v3 的 startproject 迁移到 hrp
- [x] 将 v3 的 har2case 迁移到 hrp
- [x] 将 v3 的 locust/fastapi/uvicorn 移除
- [x] #1261
- [x] hrp 运行 pytest 脚本
- [x] hrp 创建 pytest venv 环境 #1262
